version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: cloudservice-postgres
    restart: always
    environment:
      POSTGRES_DB: cloudservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cloud Service Application
  cloud-service:
    build: .
    container_name: cloud-service-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloudservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_STORAGE_LOCATION: /app/storage
      APP_SECURITY_TOKEN_SECRET: your-256-bit-secret-key-here
      APP_SECURITY_TOKEN_EXPIRATION_MS: 86400000
    volumes:
      - cloud-storage:/app/storage

volumes:
  postgres-data:
  cloud-storage:
