
server:
  port: 8080
  servlet:
    context-path: /cloud

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudservice_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  security:
    # TODO gen token
#    token-secret: your-256-bit-secret-key-here
    token-secret: 8k00tv7KQkF8w6BhaYKHdQxLgPtXerTf
    token-expiration-ms: 86400000  # 24 hours
  storage:
    location: ${user.home}/cloudservice/files