# Тестовая конфигурация
server:
  port: 8080
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Настройки загрузки файлов
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Специфичные настройки приложения
app:
  security:
    token-secret: iSgnrMvDYWRkR1gHDmUHpzJTjoojiBY4
    token-expiration-ms: 3600000  # 1 час
  storage:
    location: ${java.io.tmpdir}/cloud-service-test