server:
  port: 8080
  servlet:
    context-path: /cloud

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hdm2ddl:
          auto: update
  sql:
    init:
      mode: always
#      schema-locations: classpath:db/create-db.sql
#      data-locations: classpath:db/init-db.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

app:
  security:
    token-validity: 86400000  # 24 hours in milliseconds
  storage:
    location: ${user.home}/uploads